import com.sun.jdi.connect.spi.Connection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


  
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ESİN
 */
public class Proje extends javax.swing.JFrame {
 Connection con;
 PreparedStatement st;
    /**
     * Creates new form Proje
     */
    public Proje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        scrollPane1 = new java.awt.ScrollPane();
        scrollPane2 = new java.awt.ScrollPane();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        scrollbar1 = new java.awt.Scrollbar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTextField3.setText("jTextField3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        scrollbar1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                scrollbar1MouseWheelMoved(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ADINIZ:");

        jLabel2.setText("SOYADINIZ:");

        jLabel3.setText("YAŞINIZ:");

        jLabel4.setText("CİNSİYETİNİZ:");

        jRadioButton1.setText("Kadın");

        jRadioButton2.setText("Erkek");

        jRadioButton3.setText("Belirtmek İstemiyorum");

        jButton1.setText("Çıkış");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("İleri");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ekle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jRadioButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    JFrame frame = new JFrame("Çıkış");
        if(JOptionPane.showConfirmDialog(frame, " Çıkmak istediğinizden emin misiniz?", 
                "Connection", JOptionPane.YES_NO_OPTION) 
                == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        JFrame f= new JFrame("Anket");
        f.setVisible(true);
       
       
       
       JLabel l= new JLabel("Yaşınız?");
        JRadioButton r1=new JRadioButton("18-");
        JRadioButton r2=new JRadioButton("18-25");
        JRadioButton r3=new JRadioButton("25+");
        
        l.setBounds(50,30,300,20);
        r1.setBounds(50,50,200,20);
        r2.setBounds(50,70,200,20);
        r3.setBounds(50,90,200,20);
        
        ButtonGroup bg=new ButtonGroup();
        bg.add(r1);
        bg.add(r2);
        bg.add(r3);
        
        f.add(r1);
        f.add(r2);
        f.add(r3);
        f.add(l);
        
        f.setSize(530,1000);
        f.setLayout(null);
        f.setVisible(true);
        
        
        JLabel d1= new JLabel("Gün içerisinde internete kaç saat ayırıyorsunuz?");
        JRadioButton rr1=new JRadioButton("1-3");
        JRadioButton rr2=new JRadioButton("3-6");
        JRadioButton rr3=new JRadioButton("6+");
        
        d1.setBounds(50,140,300,20);
        rr1.setBounds(50,160,200,20);
        rr2.setBounds(50,180,200,20);
        rr3.setBounds(50,200,200,20);
        
        ButtonGroup bg0=new ButtonGroup();
        bg0.add(rr1);
        bg0.add(rr2);
        bg0.add(rr3);
        
        f.add(rr1);
        f.add(rr2);
        f.add(rr3);
        f.add(d1);

        JLabel l1= new JLabel("İnterneti en çok hangi amaçla kullanıyorsunuz?");
        JRadioButton r11=new JRadioButton("Araştırma yapmak");
        JRadioButton r12=new JRadioButton("Sosyal medyayı takip etmek");
        JRadioButton r13=new JRadioButton("Gündemi takip etmek");
        JRadioButton r14=new JRadioButton("Eğlence(video izlemek,oyun oynamak vs)");
        
        l1.setBounds(50,250,300,20);
        r11.setBounds(50,270,200,20);
        r12.setBounds(50,290,200,20);
        r13.setBounds(50,310,200,20);
        r14.setBounds(50,330,300,20);
        
        ButtonGroup bg1=new ButtonGroup();
        bg1.add(r11);
        bg1.add(r12);
        bg1.add(r13);
        bg1.add(r14);

        f.add(r11);
        f.add(r12);
        f.add(r13);
        f.add(r14);
        f.add(l1);
       
        
        JLabel b22= new JLabel("Sosyal medya denildiğinde aklınıza ilk olarak ne geliyor?");
        JRadioButton r21=new JRadioButton("Anlık Erişim/Gündem");
        JRadioButton r22=new JRadioButton("Paylaşım");
        JRadioButton r23=new JRadioButton("İletişim");
        JRadioButton r24=new JRadioButton("Eğlence");
        
        b22.setBounds(50,380,400,20);
        r21.setBounds(50,400,200,20);
        r22.setBounds(50,420,200,20);
        r23.setBounds(50,440,200,20);
        r24.setBounds(50,460,200,20);
        
        ButtonGroup bg2=new ButtonGroup();
        bg2.add(r21);
        bg2.add(r22);
        bg2.add(r23);
        bg2.add(r24);

        f.add(r21);
        f.add(r22);
        f.add(r23);
        f.add(r24);
        f.add(b22);
        
         
        JLabel g22= new JLabel("En sık kullandığınız sosyal medya uygulaması?");
        JRadioButton r31=new JRadioButton("Facebook");
        JRadioButton r32=new JRadioButton("Instagram");
        JRadioButton r33=new JRadioButton("Twitter");
        JRadioButton r34=new JRadioButton("Diğer...");
        
        g22.setBounds(50,510,400,20);
        r31.setBounds(50,530,200,20);
        r32.setBounds(50,550,200,20);
        r33.setBounds(50,570,200,20);
        r34.setBounds(50,590,200,20);
        
        ButtonGroup bg3=new ButtonGroup();
        bg3.add(r31);
        bg3.add(r32);
        bg3.add(r33);
        bg3.add(r34);

        f.add(r31);
        f.add(r32);
        f.add(r33);
        f.add(r34);
        f.add(g22);
        
       JLabel e= new JLabel("Sosyal medyada geçirdiğiniz zamanın verimli olduğunu düşünüyor musunuz?");
        JRadioButton r1e=new JRadioButton("Evet");
        JRadioButton r2e=new JRadioButton("Hayır");
        
        e.setBounds(50,640,450,20);
        r1e.setBounds(50,660,200,20);
        r2e.setBounds(50,680,200,20);
        
        ButtonGroup bge=new ButtonGroup();
        bge.add(r1e);
        bge.add(r2e);
        
        f.add(r1e);
        f.add(r2e);
        f.add(e);
        
      JButton jb =new JButton("Kaydet");
      jb.setBounds(400,740,75,25);
      f.add(jb);
      jb.addActionListener(new ActionListener(){
          
          public void actionPerformed(ActionEvent actionEvent){
              if(JOptionPane.showConfirmDialog(f, " Kaydetmek istediğinizden emin misiniz?", 
                "Connection", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION)
                          {
            JOptionPane.showMessageDialog(f,"Kaydedildi!");
            System.exit(0);
        }              
          }
            
      });
      
           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void scrollbar1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_scrollbar1MouseWheelMoved

    }//GEN-LAST:event_scrollbar1MouseWheelMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: 
        
        try{
           // con = DriverManager.getConnection("jdbc:mysql://localhost:3306/anket, "root", "4321");
           // st = con.prepareStatement("insert into anket (isim, soyisim, yaş) values (?, ?, ?)");
            
           // st.setString(1, JTextField1.getText());
           // st.setString(2, JTextField2.getText());
           // st.setString(3, JTextField4.getText());
          
            
           // st.execute();
            JOptionPane.showMessageDialog(null, "Ekleme Başarılı");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            
        }
        
    

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.ScrollPane scrollPane2;
    private java.awt.Scrollbar scrollbar1;
    // End of variables declaration//GEN-END:variables
}
